# Generated by Django 4.2.7 on 2023-11-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('comapny', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
            ],
        ),
    ]
