# Generated by Django 5.0 on 2023-12-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='methodsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('establishedyear', models.CharField(max_length=100)),
                ('ceo', models.CharField(max_length=100)),
            ],
        ),
    ]
